chore: update documentation to account for self generating vuln DB
quay/clair-action pull request #163
Opened 2024-06-17 20:48 UTC by crozzy

Previously we had hosted a security DB that was updated nightly but as previously stated, this is no longer tenable. In place of this we added some machinary to allow users to (hopefully) easily generate it. This change updates the README to reflect those changes.

2024-06-20 14:48 UTC, crozzy commented
closes https://github.com/quay/clair-action/issues/99

2024-06-24 19:45 UTC, hdonnay requested changes
Some changes needed, I think.

2024-06-24 19:45 UTC, hdonnay commented on README.md
> +git ## About
Looks like typo/bad addition?

2024-06-24 19:45 UTC, hdonnay commented on README.md
> +As the vulnerability database isn't hosted anywhere it is the responsibility of the user to generate it. clair-action surfaces an update mode to allow users to do this.
```suggestion
As the vulnerability database isn't hosted anywhere, it is the responsibility of the user to generate it.
`Clair-action` surfaces an update mode to allow users to do this.
```

2024-06-24 19:45 UTC, hdonnay commented on README.md
> +        uses: quay/clair-action@allow-update
```suggestion
        uses: quay/clair-action@main
```
This should probably have the same ref as the codeblock above?

2024-06-24 19:45 UTC, hdonnay commented on README.md
> +
```suggestion
```

2024-06-24 20:01 UTC, hdonnay approved these changes

2024-06-24 20:06 UTC, crozzy commented
/fast-forward

2024-06-24 20:06 UTC, merged